# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappl', '0003_auto_20170926_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='ads',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myappl.Location'),
        ),
    ]
