# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappl', '0004_auto_20170927_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappl.Location'),
        ),
    ]
