# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappl', '0005_auto_20170927_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
