# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappl', '0006_userprofile_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user',), 'verbose_name': 'UserProfile', 'verbose_name_plural': 'usersprofile'},
        ),
    ]
