# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappl', '0009_auto_20170927_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
