# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-28 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappl', '0010_ads_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Slug',
            new_name='slug',
        ),
    ]
