# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-30 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappl', '0011_auto_20170928_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappl.Location'),
        ),
    ]
