# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-30 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappl', '0012_auto_20170930_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
